---
- name: be and web Troubleshooting Tools Setup
  hosts: be_ec2, web_ec2
  become: true
  become_user: root
  roles:
    - tools

- name: RDS Data Injection
  hosts: be_ec2
  become: true
  vars:
    rds_dns: "{{ hostvars[groups['rds_ec2'][0]]['endpoint']['address'] }}"
    be_priv_ip: "{{ hostvars[groups['be_ec2'][0]]['private_ip_address'] }}"
  roles:
    - data_injection

- name: be Advanced Setup
  hosts: be_ec2
  become: true
  vars:
    rds_dns: "{{ hostvars[groups['rds_ec2'][0]]['endpoint']['address'] }}"
  roles:
    - be

- name: web Advanced Setup
  hosts: web_ec2
  become: true
  become_user: root
  vars:
    be_dns: "{{ hostvars[groups['be_ec2'][0]]['public_dns_name'] }}"
  roles:
    - web