---
- name: Install DB Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-server
    - python3-pymysql
  tags:
    - db_packages

- name: Create App DB
  community.mysql.mysql_db:
    login_host: "{{ rds_dns }}"
    login_user: root
    login_password: rootpass123
    name: backend
    state: present
  tags:
    - db_setup

- name: Create App User
  community.mysql.mysql_user:
    login_host: "{{ rds_dns }}"
    login_user: root
    login_password: rootpass123
    name: example
    password: secure
    host: "{{ be_priv_ip }}"
    priv: 'backend.*:ALL'
    state: present
  tags:
    - db_setup

- name: Create App Table
  community.mysql.mysql_query:
    login_host: "{{ rds_dns }}"
    login_db: backend
    login_user: example
    login_password: secure
    query: |
      CREATE TABLE item (
        name varchar(30) NOT NULL,
        bcit_id varchar(10) NOT NULL,
        PRIMARY KEY(bcit_id)
      );
  tags:
    - db_data

- name: Insert App Data
  community.mysql.mysql_query:
    login_host: "{{ rds_dns }}"
    login_db: backend
    login_user: example
    login_password: secure
    query: INSERT INTO item (name, bcit_id) VALUES ('NAMEHEREMAX30', 'IDPLSMAX10');
  tags:
    - db_data

- name: Flush Privileges
  community.mysql.mysql_query:
    login_host: "{{ rds_dns }}"
    login_user: root
    login_password: rootpass123
    query: FLUSH PRIVILEGES;
  tags:
    - db_fix